databases:
  - name: postgres
    ipAllowList: []
    databaseName: navy_steel_doberman
    user: navy_steel_doberman

services:
  - type: web
    name: navy_steel_doberman
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false